export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_MATERIALS = "LOAD_MATERIALS";

// user
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
